name: 'Cleanup Workflow History'
description: 'Deletes old GitHub Actions workflow runs based on age.'
author: 'smiggleworth'

branding:
  icon: 'trash'
  color: 'red'

inputs:
  days_old:
    description: 'Number of days to keep workflow runs (runs older than this will be deleted)'
    required: false
    default: '7'
  per_page:
    description: 'Number of workflow runs to fetch per request (max 100)'
    required: false
    default: '50'

runs:
  using: 'composite'
  steps:
    - name: Delete Old Workflow Runs
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        CUTOFF_DATE=$(date -u -d "-${{ inputs.days_old }} days" +%Y-%m-%dT%H:%M:%SZ)
        
        while true; do
          IDS=$(gh run list \
            --limit ${{ inputs.per_page }} \
            --json databaseId,createdAt \
            --jq ".[] | select(.createdAt < \"$CUTOFF_DATE\") | .databaseId")
        
          if [ -z "$IDS" ]; then
            echo "No more old runs to delete."
            break
          fi
        
          echo "$IDS" | while read -r ID; do
            echo "Deleting workflow run ID=$ID"
            gh run delete "$ID" --yes && echo "Deleted ID=$ID" || echo "Failed to delete ID=$ID"
          done
        done

